services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
      condition: service_healthy
    ports:
      - "3000:3000"
