services:
  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    ports:
      - "3001:3000"

  api:
    hostname: api
    build:
      context: backend
      dockerfile: Dockerfile
    privileged: true  # Required for Docker in Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    expose:
      - 3000
