[project]
name = "FactorioServerManager"
requires-python = ">=3.12"
# authors = [{name = "name", email = "name@address.com"}]
version = "0.0.0"

[tool.pyright]
reportMissingTypeStubs = "none"

[tool.ruff]
indent-width = 4
line-length = 300
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "ANN102",
    "D212",
    "D413",
    "G004",
    "D203",
    "ISC001", # ignore implicit string concatenation, conflicts with formatter
    "COM812", # ignore missing comma in list, conflicts with formatter
]
select = ["ALL"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]  # imports not at top of cell and unused imports

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false


[tool.tomlsort]
all = true
in_place = true
no_block_comments = false
no_comments = false
no_footer_comments = false
no_header_comments = false
no_inline_comments = false
no_sort_tables = true
sort_inline_arrays = true
sort_inline_tables = true
sort_table_keys = true
spaces_before_inline_comment = 2
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
