FROM python:3.13-slim

# Setup Uv
COPY --from=ghcr.io/astral-sh/uv:0.5.29 /uv /uvx /bin/

# Setup project
ADD . /app
WORKDIR /app

# Sync the project into a new environment, using the frozen lockfile
RUN uv venv
RUN uv sync --frozen

ENTRYPOINT uv run .
